#!/usr/bin/gawk -f

BEGIN {
	FS = "[<>]";
	PROCINFO["sorted_in"]= "@ind_str_asc";
	head = "<h1 align="center"> Extracto ViaVerde </h1>\n<hr><h2> Cliente </h2>\n";
  	enc = "<html> <head> <meta charset='UTF-8'/> </head> <body>";
  	fmt = "<li><a> Entradas no dia %s: %d </a></li>\n";
  	lista ="\n<li><a> Locais </a><li>\n";
  	entrada = "<li><a> -> %s </a><li>\n";
  	end = "</body> </html>";
  	elemento = "null";
  	nome = "semNome"
}

/^<NOME/{
	nome = $3;
}

/^<DATA_ENTRADA/ && $3!="null"{
	split($3,a,"-");
	dias[a[1]]++;
	mes = a[2];
}

/^<SAIDA/{
	locais[$3]++;
}

/^<IMPORTANCIA/{
	elemento = $3;
	sub(/,/,".",elemento)
	valor[mes] += elemento;
}

/^<TIPO>[Pp]arque/{
	parques[$3] += elemento;
}

END{
	print enc > "index.html";
	
	printf(head,nome) > "index.html"

  	for (i in dias) 
  		printf (fmt,i,dias[i]) > "index.html";
  	
  	print lista > "index.html";
  	for(i in locais){
  		printf (entrada,i) > "index.html";
  	}

  	for(i in valor){
  		print "valor: " valor[i];
  	}

  	for(i in parques){
  		print "parque: " i " -> " parques[i];
  	}

  	print end > "index.html";
}