#!/usr/bin/gawk -f

BEGIN {
	RS = "<";
	FS = ">";
}

/^DATA_ENTRADA/ && $2!="null"{
	split($2,a,"-");
	for(i in a)
		ins[i] = a[i] "\n ";
	dias[a[1]]++;
}

/^SAIDA/{
	locais[$2]++;
}

/^TRANSACCAO/{
	print "tran" $3 " | " $4
}

END{
  for(i in dias){
  	print "Entradas dia " i " : " dias[i]; 
  }

  for(i in locais){
  	print "Locais: " i;
  }
}